// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rev_cumsum
arma::vec rev_cumsum(const arma::vec& X);
RcppExport SEXP _coxkll_rev_cumsum(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(rev_cumsum(X));
    return rcpp_result_gen;
END_RCPP
}
// ddloglik
List ddloglik(const arma::mat& Z, const arma::vec& delta, const arma::vec& beta);
RcppExport SEXP _coxkll_ddloglik(SEXP ZSEXP, SEXP deltaSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(ddloglik(Z, delta, beta));
    return rcpp_result_gen;
END_RCPP
}
// ddloglik_S0
List ddloglik_S0(const arma::mat& Z, const arma::vec& delta, const arma::vec& beta);
RcppExport SEXP _coxkll_ddloglik_S0(SEXP ZSEXP, SEXP deltaSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(ddloglik_S0(Z, delta, beta));
    return rcpp_result_gen;
END_RCPP
}
// maxgrad
double maxgrad(const arma::mat& X, const arma::vec& y, const arma::vec& K, const arma::vec& m);
RcppExport SEXP _coxkll_maxgrad(SEXP XSEXP, SEXP ySEXP, SEXP KSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type K(KSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(maxgrad(X, y, K, m));
    return rcpp_result_gen;
END_RCPP
}
// standardize
List standardize(const arma::mat& x);
RcppExport SEXP _coxkll_standardize(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(standardize(x));
    return rcpp_result_gen;
END_RCPP
}
// gdfit_cox_kl
List gdfit_cox_kl(const arma::mat& X, const arma::vec& d, const arma::vec& delta_tilde, const arma::uvec& K1, const int& K0, const arma::vec& lambda, const double& alpha, const double& eps, const double& eta_kl, const int& max_iter, const double& gamma, const arma::vec& group_multiplier, const int& dfmax, const int& gmax, const bool& warn, const bool& user, const int& actIter);
RcppExport SEXP _coxkll_gdfit_cox_kl(SEXP XSEXP, SEXP dSEXP, SEXP delta_tildeSEXP, SEXP K1SEXP, SEXP K0SEXP, SEXP lambdaSEXP, SEXP alphaSEXP, SEXP epsSEXP, SEXP eta_klSEXP, SEXP max_iterSEXP, SEXP gammaSEXP, SEXP group_multiplierSEXP, SEXP dfmaxSEXP, SEXP gmaxSEXP, SEXP warnSEXP, SEXP userSEXP, SEXP actIterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d(dSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta_tilde(delta_tildeSEXP);
    Rcpp::traits::input_parameter< const arma::uvec& >::type K1(K1SEXP);
    Rcpp::traits::input_parameter< const int& >::type K0(K0SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const double& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const double& >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< const double& >::type eta_kl(eta_klSEXP);
    Rcpp::traits::input_parameter< const int& >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const double& >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type group_multiplier(group_multiplierSEXP);
    Rcpp::traits::input_parameter< const int& >::type dfmax(dfmaxSEXP);
    Rcpp::traits::input_parameter< const int& >::type gmax(gmaxSEXP);
    Rcpp::traits::input_parameter< const bool& >::type warn(warnSEXP);
    Rcpp::traits::input_parameter< const bool& >::type user(userSEXP);
    Rcpp::traits::input_parameter< const int& >::type actIter(actIterSEXP);
    rcpp_result_gen = Rcpp::wrap(gdfit_cox_kl(X, d, delta_tilde, K1, K0, lambda, alpha, eps, eta_kl, max_iter, gamma, group_multiplier, dfmax, gmax, warn, user, actIter));
    return rcpp_result_gen;
END_RCPP
}
// calculateDeltaTilde
arma::vec calculateDeltaTilde(const arma::vec& event, const arma::vec& time, const arma::vec& theta_tilde);
RcppExport SEXP _coxkll_calculateDeltaTilde(SEXP eventSEXP, SEXP timeSEXP, SEXP theta_tildeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type event(eventSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_tilde(theta_tildeSEXP);
    rcpp_result_gen = Rcpp::wrap(calculateDeltaTilde(event, time, theta_tilde));
    return rcpp_result_gen;
END_RCPP
}
// calculateRiskAndUpdateLoss
List calculateRiskAndUpdateLoss(arma::vec& eta, const arma::vec& d, double Loss, arma::vec r);
RcppExport SEXP _coxkll_calculateRiskAndUpdateLoss(SEXP etaSEXP, SEXP dSEXP, SEXP LossSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d(dSEXP);
    Rcpp::traits::input_parameter< double >::type Loss(LossSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(calculateRiskAndUpdateLoss(eta, d, Loss, r));
    return rcpp_result_gen;
END_RCPP
}
// calculateRiskAndUpdateLoss2
List calculateRiskAndUpdateLoss2(arma::vec& eta, arma::vec& d, arma::vec& deltaTilde, double& Loss, double& gamma);
RcppExport SEXP _coxkll_calculateRiskAndUpdateLoss2(SEXP etaSEXP, SEXP dSEXP, SEXP deltaTildeSEXP, SEXP LossSEXP, SEXP gammaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type d(dSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type deltaTilde(deltaTildeSEXP);
    Rcpp::traits::input_parameter< double& >::type Loss(LossSEXP);
    Rcpp::traits::input_parameter< double& >::type gamma(gammaSEXP);
    rcpp_result_gen = Rcpp::wrap(calculateRiskAndUpdateLoss2(eta, d, deltaTilde, Loss, gamma));
    return rcpp_result_gen;
END_RCPP
}
// ddloglik_md
List ddloglik_md(int n, arma::colvec& delta, arma::mat& z, arma::colvec& beta, arma::mat& offset);
RcppExport SEXP _coxkll_ddloglik_md(SEXP nSEXP, SEXP deltaSEXP, SEXP zSEXP, SEXP betaSEXP, SEXP offsetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type z(zSEXP);
    Rcpp::traits::input_parameter< arma::colvec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type offset(offsetSEXP);
    rcpp_result_gen = Rcpp::wrap(ddloglik_md(n, delta, z, beta, offset));
    return rcpp_result_gen;
END_RCPP
}
// ddloglik_md2
List ddloglik_md2(arma::vec& delta, arma::mat& z, arma::vec& beta);
RcppExport SEXP _coxkll_ddloglik_md2(SEXP deltaSEXP, SEXP zSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< arma::mat& >::type z(zSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(ddloglik_md2(delta, z, beta));
    return rcpp_result_gen;
END_RCPP
}
// klcox_boosting
List klcox_boosting(const arma::mat& z, const arma::vec& delta, const arma::vec& theta_tilde, const double& eta, const double& rate, const double& tol, const int& maxit);
RcppExport SEXP _coxkll_klcox_boosting(SEXP zSEXP, SEXP deltaSEXP, SEXP theta_tildeSEXP, SEXP etaSEXP, SEXP rateSEXP, SEXP tolSEXP, SEXP maxitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_tilde(theta_tildeSEXP);
    Rcpp::traits::input_parameter< const double& >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const double& >::type rate(rateSEXP);
    Rcpp::traits::input_parameter< const double& >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int& >::type maxit(maxitSEXP);
    rcpp_result_gen = Rcpp::wrap(klcox_boosting(z, delta, theta_tilde, eta, rate, tol, maxit));
    return rcpp_result_gen;
END_RCPP
}
// ddloglik_KL_RS_test
double ddloglik_KL_RS_test(double z);
RcppExport SEXP _coxkll_ddloglik_KL_RS_test(SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(ddloglik_KL_RS_test(z));
    return rcpp_result_gen;
END_RCPP
}
// loss_fn_cpp
List loss_fn_cpp(const arma::mat& Z, const arma::vec& delta, arma::vec& beta);
RcppExport SEXP _coxkll_loss_fn_cpp(SEXP ZSEXP, SEXP deltaSEXP, SEXP betaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type beta(betaSEXP);
    rcpp_result_gen = Rcpp::wrap(loss_fn_cpp(Z, delta, beta));
    return rcpp_result_gen;
END_RCPP
}
// ddloglik_KL_RS_score
List ddloglik_KL_RS_score(const arma::mat& Z, const arma::vec& delta, arma::vec& beta, const arma::vec& theta_tilde, const double& eta);
RcppExport SEXP _coxkll_ddloglik_KL_RS_score(SEXP ZSEXP, SEXP deltaSEXP, SEXP betaSEXP, SEXP theta_tildeSEXP, SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_tilde(theta_tildeSEXP);
    Rcpp::traits::input_parameter< const double& >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(ddloglik_KL_RS_score(Z, delta, beta, theta_tilde, eta));
    return rcpp_result_gen;
END_RCPP
}
// ddloglik_KL_RS
List ddloglik_KL_RS(const arma::mat& Z, const arma::vec& delta, arma::vec& beta, const arma::vec& theta_tilde, double& eta);
RcppExport SEXP _coxkll_ddloglik_KL_RS(SEXP ZSEXP, SEXP deltaSEXP, SEXP betaSEXP, SEXP theta_tildeSEXP, SEXP etaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type theta_tilde(theta_tildeSEXP);
    Rcpp::traits::input_parameter< double& >::type eta(etaSEXP);
    rcpp_result_gen = Rcpp::wrap(ddloglik_KL_RS(Z, delta, beta, theta_tilde, eta));
    return rcpp_result_gen;
END_RCPP
}
// KL_Cox_Estimate_cpp
arma::vec KL_Cox_Estimate_cpp(const arma::mat& z, const arma::vec& delta, const arma::vec& time, const arma::vec& RS_internal, double eta, const double tol, const bool returnBeta);
RcppExport SEXP _coxkll_KL_Cox_Estimate_cpp(SEXP zSEXP, SEXP deltaSEXP, SEXP timeSEXP, SEXP RS_internalSEXP, SEXP etaSEXP, SEXP tolSEXP, SEXP returnBetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type z(zSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type time(timeSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type RS_internal(RS_internalSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const bool >::type returnBeta(returnBetaSEXP);
    rcpp_result_gen = Rcpp::wrap(KL_Cox_Estimate_cpp(z, delta, time, RS_internal, eta, tol, returnBeta));
    return rcpp_result_gen;
END_RCPP
}
// cox_custom_obj
List cox_custom_obj(const arma::vec& theta, const arma::vec& delta, const arma::vec& penalty_weights, double lambda);
RcppExport SEXP _coxkll_cox_custom_obj(SEXP thetaSEXP, SEXP deltaSEXP, SEXP penalty_weightsSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type penalty_weights(penalty_weightsSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(cox_custom_obj(theta, delta, penalty_weights, lambda));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_coxkll_rev_cumsum", (DL_FUNC) &_coxkll_rev_cumsum, 1},
    {"_coxkll_ddloglik", (DL_FUNC) &_coxkll_ddloglik, 3},
    {"_coxkll_ddloglik_S0", (DL_FUNC) &_coxkll_ddloglik_S0, 3},
    {"_coxkll_maxgrad", (DL_FUNC) &_coxkll_maxgrad, 4},
    {"_coxkll_standardize", (DL_FUNC) &_coxkll_standardize, 1},
    {"_coxkll_gdfit_cox_kl", (DL_FUNC) &_coxkll_gdfit_cox_kl, 17},
    {"_coxkll_calculateDeltaTilde", (DL_FUNC) &_coxkll_calculateDeltaTilde, 3},
    {"_coxkll_calculateRiskAndUpdateLoss", (DL_FUNC) &_coxkll_calculateRiskAndUpdateLoss, 4},
    {"_coxkll_calculateRiskAndUpdateLoss2", (DL_FUNC) &_coxkll_calculateRiskAndUpdateLoss2, 5},
    {"_coxkll_ddloglik_md", (DL_FUNC) &_coxkll_ddloglik_md, 5},
    {"_coxkll_ddloglik_md2", (DL_FUNC) &_coxkll_ddloglik_md2, 3},
    {"_coxkll_klcox_boosting", (DL_FUNC) &_coxkll_klcox_boosting, 7},
    {"_coxkll_ddloglik_KL_RS_test", (DL_FUNC) &_coxkll_ddloglik_KL_RS_test, 1},
    {"_coxkll_loss_fn_cpp", (DL_FUNC) &_coxkll_loss_fn_cpp, 3},
    {"_coxkll_ddloglik_KL_RS_score", (DL_FUNC) &_coxkll_ddloglik_KL_RS_score, 5},
    {"_coxkll_ddloglik_KL_RS", (DL_FUNC) &_coxkll_ddloglik_KL_RS, 5},
    {"_coxkll_KL_Cox_Estimate_cpp", (DL_FUNC) &_coxkll_KL_Cox_Estimate_cpp, 7},
    {"_coxkll_cox_custom_obj", (DL_FUNC) &_coxkll_cox_custom_obj, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_coxkll(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
