# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rev_cumsum <- function(X) {
    .Call(`_VariableSelection_rev_cumsum`, X)
}

ddloglik <- function(Z, delta, beta) {
    .Call(`_VariableSelection_ddloglik`, Z, delta, beta)
}

maxgrad <- function(X, y, K, m) {
    .Call(`_VariableSelection_maxgrad`, X, y, K, m)
}

standardize <- function(x) {
    .Call(`_VariableSelection_standardize`, x)
}

gdfit_cox <- function(X, d, penalty, K1, K0, lambda, alpha, eps, max_iter, gamma, group_multiplier, dfmax, gmax, warn, user, actIter = 50L) {
    .Call(`_VariableSelection_gdfit_cox`, X, d, penalty, K1, K0, lambda, alpha, eps, max_iter, gamma, group_multiplier, dfmax, gmax, warn, user, actIter)
}

gdfit_cox_kl <- function(X, d, penalty, delta_tilde, K1, K0, lambda, alpha, eps, eta_kl, max_iter, gamma, group_multiplier, dfmax, gmax, warn, user, actIter = 20L) {
    .Call(`_VariableSelection_gdfit_cox_kl`, X, d, penalty, delta_tilde, K1, K0, lambda, alpha, eps, eta_kl, max_iter, gamma, group_multiplier, dfmax, gmax, warn, user, actIter)
}

#' An Rcpp function that calculates the first and second order derivate and partial likelihood function.
#' @param N   The sample size
#' @param delta   Event indicator
#' @param z   Covariate matrix
#' @param beta   The coefficient
#' @param offset   The whole spanned matrix
#' 
#' @return the first and second derivate and partial likelihood
ddloglik_md <- function(n, delta, z, beta, offset) {
    .Call(`_VariableSelection_ddloglik_md`, n, delta, z, beta, offset)
}

ddloglik_md2 <- function(delta, z, beta) {
    .Call(`_VariableSelection_ddloglik_md2`, delta, z, beta)
}

klcox_boosting <- function(z, delta, theta_tilde, eta, rate, tol, maxit) {
    .Call(`_VariableSelection_klcox_boosting`, z, delta, theta_tilde, eta, rate, tol, maxit)
}

ddloglik_KL_RS_test <- function(z) {
    .Call(`_VariableSelection_ddloglik_KL_RS_test`, z)
}

ddloglik_KL_RS <- function(Z, delta, beta, theta_tilde, eta) {
    .Call(`_VariableSelection_ddloglik_KL_RS`, Z, delta, beta, theta_tilde, eta)
}

